### ISSUE TITLE
Price on a Product POSTed with Procurement.ProductsItem.CreateRequest doesn't hold

### ISSUE THREAD

**Issue by Villawhatever** [orionstudt/ConnectWise.Http#10]
```
var prod = new Product {
    // ...
    Price = 123
    // ...
}

var serializedProduct = JsonConvert.SerializeObject(product);
var request = Procurement.ProductsItem.CreateRequest(serializedProduct);
```

Expected behavior: The posted Product has its price set to the value specified.
Actual behavior: The price defaults to the price of the CatalogItem reference.

Current workaround is PATCHing the Product once the POST is successful. Is something missing in the wrapper, or is this expected behavior of ConnectWise Manage API proper?

**Comment by orionstudt** [comment]
Hi @Villawhatever .

Not sure what the issue here is. The lib has delegated all serialization responsibility to the consumer, so all it does is put the string result into a `StringContent` as part of the `HttpRequestMessage`. 

You could maybe examine the request that is created in your example, and see if the serialized result in the request matches what you are expecting should be sent. Should be `request.Content.ReadAsStringAsync()`. If you can confirm that the serialized request body that is sent matches what the API expects and this still isn't working, than it must be an issue with the ConnectWise Manage API.

If your serialized request body doesn't match what the API is expecting, than maybe an issue with the model you're serializing?

**Comment by Villawhatever** [comment]
Have confirmed this is a problem with CW Api itself. Sorry to bother you :)

**Comment by orionstudt** [comment]
Thanks for the update!
