### ISSUE TITLE
Project Tickets

### ISSUE THREAD

**Issue by ajwaka** [orionstudt/ConnectWise.Http#2]
I spent much too much time trying to figure out why a call to the `ServiceModule.Tickets.GetRequest` wouldn't return Project tickets.  I decided to clone this project and implement `ProjectsModule.Tickets` to get things to work - which did.  But ran into other issues on different calls (finding tickets on an agreement that are open or closed within teh last month).

I FINALLY figured out the reason and was thinking you may want to document it or change the default.

When creating `CWApiSettings` the default is `accept = "application/json"` - which while can work for many items - also doesn't allow many other queries to work properly.  Namely - it won't return Project tickets in the `Service/tickets` call.

Setting `accept = "application/vnd.connectwise.com+json; version=3.0.0"` fixed the issue of Project tickets not being returned in a simple `ServiceModule.Tickets.GetRequest` as well as my other filtering.

Here's the 2 examples of queries I was doing.  I am only setting the `Conditions` property in these queries.

`Conditions = "resources like '%awalker%' and status/name != 'Closed' and status/name !='Completed'`
This was only returning SERVICE tickets.

`Conditions = "Agreement/Id = 1460 and (ClosedDate = NULL or (ClosedDate < [06/30/2019] and ClosedDate >= [06/01/2019])) and DateEntered <= [06/30/2019]"`
PostMan was returning 57 items (correctly) while ConnectWise.HTTP was returning an empty array, but a successful call.  Again - changing my `accepts` value properly returned all tickets that matched the query.

Thanks for creating this project!  I've been having many issues w/ the changes CW has been making lately and using their SDK's.  Some features quit working but are still available.  This allows me to get all my implementations back up and running.

**Comment by orionstudt** [comment]
Hi @ajwaka - sorry I don't pay as much attention to this as I should.

There was a similar issue that I encountered with my own usage but it was the inverse, using their `application/vnd.connectwise.com+json; version=3.0.0` was causing unexpected results on some endpoints. If you look in `CWHttpClient` you'll see that I actually commented it out and noted that. Before commenting it out the `Accept` property wasn't an option on `CWApiSettings` so I added that at the same time so it could be set as needed.

I could probably change the default to their recommended one as _hopefully_ it works on more endpoints than the `application/json` default does. I may do that next time I get around to updating this. Might be worthwhile to make it a property on the `CWRequest` object as well/instead so that it can more easily be set on a per-request basis.

It's definitely a pain how much they change their APIs but I think they're slowly going in the right direction.

I am no longer with my previous employer where I was interacting with ConnectWise Manage daily, so feel free to fork and do whatever you need to do because any future updates will probably just be when I'm bored or not busy. All of that said, glad you've found it useful!

**Comment by orionstudt** [comment]
In the meantime I will put a note in the readme.
