### ISSUE TITLE
Test Suite & .Net Core support question

### ISSUE THREAD

**Issue by skalavala** [orionstudt/ConnectWise.Http#3]
First of all, Thank you for taking time to share your personal project with the community. I apologize in advance, this is not an issue, but a request. Do you have a test program that you can share to test all the functionality? If you have any test driver program or unit test cases, that would be very valuable for those (like me) who is new to ConnectWise that are trying to explore this package.

Also, do you know if this is supported in .net core? Thanks in advance.

**Comment by orionstudt** [comment]
Hi @skalavala,

Unfortunately I do not have a test project. When I was originally working on this I had a sandbox CWM instance that I was testing against but I never had formal unit tests. You are more than welcome to try to put something together if you would like.

The newest version is .NET Standard so yes, .NET Core can reference this library. However I still need to go in and set `.ConfigureAwait(false)` on all of the `HttpClient` calls. Currently those calls will block your main thread so you'll want to make sure that UI applications are calling on a background worker. I will try to see if I can push that this weekend so that will not be necessary.

I've entertained the idea of doing a 2.X version and incorporating some of the things I've learned since I originally wrote this so maybe after I do that I will start on this.

**Comment by skalavala** [comment]
Thank you for the quick response. I am literally in day-2 of looking into the ConnectWise product. I have never used it, and not very familiar with the functionality either. All I was trying to do at this moment is to be able to create ticket and get ticket status using the API. Your basic examples in the readme helped me on how to set it up, and make basic calls, and get ticket information. I am using .net core, and it worked flawlessly and will wait for you to update the readme on using `.ConfigureAwait(false)` information and will try again.

**Whatever you have will certainly help me and any pointers, code, examples you can provide is much appreciated!** 🙏 

Being new to CW, having a bit of trouble finding right resources, documentation, code and stuff. I am not sure how I can create a ticket using the API - and hence my request about the test code 😄 

I believe best piece of documentation is code itself ;)

Again, thank you so much for sharing this and it is a great start for me for sure!

**Comment by orionstudt** [comment]
Hi @skalavala,

It sounds like you should be able to accomplish everything you need for your use-case with the current iteration. That said I just published `1.1.0` with the `ConfigureAwait(false)` on every `async` call so unnecessary UI blocking shouldn't be an issue.

As for code samples, I'm not sure I can help you too much in that regard as most of my work was under NDA for my employer at the time. But I would highly recommend making a developer account on the ConnectWise developer website and digging into their documentation as it has been coming along nicely I think. Keep in mind that I am not affiliated with ConnectWise in any way and this libarary was written via the information provided in that documentation, so you should be able to use that to figure out most everything that you need to.

I structured the various modules for request generation the same way the ConnectWise separates and organizes their API & documentation so that much should be self-evident.

Good luck, and let me know if you have anymore bugs/issues with this library!

**Comment by skalavala** [comment]
Thank you, I created the developer account, and exploring the documentation. I truly appreciate your quick response and the updates to the package. **Thank you so much!**
