### ISSUE TITLE
404 bad request 

### ISSUE THREAD

**Issue by defjam903** [orionstudt/ConnectWise.Http#4]
{Method: POST, RequestUri: 'https://api-na.myconnectwise.net/v2019_4/apis/3.0/service/tickets', Version: 1.1, Content: System.Net.Http.ObjectContent`1[System.Object], Headers:
{
  Authorization: Basic **redacted**
  Accept: application/json
  User-Agent: ConnectWise-DotNet-SDK
  Content-Type: application/json; charset=utf-8
  Content-Length: 516
}}

**Comment by orionstudt** [comment]
Hi @defjam903,

Is that a sandbox instance? I would probably try to refrain from posting your access tokens here in the future.

Can you extrapolate anymore on what the issue is, what the response was, & finally what you're trying to do?

The title alone isn't clear - is it a 404 (Not Found) or a 400 (Bad Request)?

One of the first things I'm noticing off the bat is that your `POST` content is `ObjectContent` when it should be `StringContent` (JSON).

**Comment by defjam903** [comment]
Hello, 

sorry I thought I pulled my token out so I am getting the error on the below lines stating that I am not authorized but this was working before the latest update

          Dim response = ticketApi.CreateTicket(ticket)
          Dim newTicket = response.GetResult(Of Ticket)()

**Comment by orionstudt** [comment]
That syntax doesn't look familiar to me, as with my library you would first create the request, and then send the request with a normalized `SendAsync(...)` function on my `CWHttpClient`.

Are you sure you are using this library? Your request above says `User-Agent: ConnectWise-DotNet-SDK` which may imply otherwise...
