### ISSUE TITLE
Ambiguous on all SendAsync calls

### ISSUE THREAD

**Issue by ajwaka** [orionstudt/ConnectWise.Http#6]
It seems a recent change has broke all existing calls in my site due to "ambiguous calls".  I've added a comment here: https://github.com/orionstudt/ConnectWise.Http/commit/b5e0888e6b89857ffe4fb7fc397c62eb7df2fe40

The "overload" takes a `default` second parameter, but becomes ambiguous between the two.  Maybe it could just be required to keep from breaking others?

**Comment by orionstudt** [comment]
Hmmm I'm confused about why we're seeing an ambiguous alert on that overload given that I didn't modify the original overload, both overloads have a default value, and both overloads are a different type. You're getting ambiguity on `CancellationTokenSource`?

**Comment by ajwaka** [comment]
Here's a screenshot when I remove the `null`: https://www.screencast.com/t/zjHyd8wErW

My project is .net 4.6.1 - and once I add `null`, it'll compile.

**Comment by orionstudt** [comment]
Ah, I see. It seems I accidentally added a breaking change - doing exactly what I was hoping to avoid lol. When you provide `null` it knows you want the `CancellationTokenSource` overload instead, since `CancellationToken` cannot be `null`.

I think I will remove the `CancellationTokenSource` overload. Providing a `CancellationToken` is more correct. This will break anyone that was providing a `CancellationTokenSource` but I suppose since I already made a breaking change I might as well bite the bullet and get it done.  I'll get that done today after work.

**Comment by orionstudt** [comment]
Just published to NuGet - sorry it took so long. Currently validating. Your current calls will be broken however, as you were falling back on the `CancellationTokenSource` overload. So you will need to get rid of the null so you just fall back on the `CancellationToken` default. Sorry about that but should be good now, noted your contribution in release notes!
